version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Python Dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt  # Adjust this based on your project setup

      # Install Node.js and npm (for Playwright)
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install Playwright
      - run:
          name: Install Playwright
          command: |
            npm install -g playwright

      # Run Playwright tests
      - run:
          name: Run Playwright Tests
          command: |
            playwright install
            playwright test
